name: GitHub Actions Lint
permissions: {}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ghalint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: koki-develop/github-actions-lint/ghalint@f250fd58748eec35c7845aade6b6ac2b9dec09e3
